[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = db
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$EeJ8j5HSem.NEUIIQWiNcQ$MYYj7a7uSUCl9Sl2luukwQ88thGk0r71gDsdMoQQsPNXYR6oSZMqwgHzy8kfoYCx5v6ldFdB5rYvaT2MZVeDhA

